baseurl = "https://thadbrown.com"
languageCode = "en"
title = "/Thad /Chapman /Brown"
theme = "hucore"
copyright = "&copy; 2017 | Follow on <a href=\"https://twitter.com/thad_brown\" target=\"_blank\">Twitter</a> | <a href=\"https://github.com/mgjohansen/hucore.git\" target=\"_blank\">Hucore theme</a> & <a href=\"http://gohugo.io\" target=\"_blank\">Hugo</a> ♥"

[taxonomies]
tag = "tags"

[params]
description = "a novel without a hero"
keywords = ["music", "tech", "travel"]
author = "Thad Brown"
sharingicons = true
displayauthor = true

[params.highlight]
style = "github"
languages = ["go", "dockerfile"]

[[params.social]]
url = "https://github.com/tcbtcb"
fa_icon = "fa-github"

[[params.social]]
url = "https://twitter.com/thad_brown"
fa_icon = "fa-twitter"

[[params.social]]
url = "https://www.linkedin.com/in/thad-brown-986306105"
fa_icon = "fa-linkedin-square"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"

[[params.socialshare]]
url = "https://www.linkedin.com/in/thad-brown-986306105"
fa_icon = "fa-linkedin-square"
